spring:
  application:
    name: hp-vvs-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hp_vvs}
    username: ${DB_USERNAME:hpvvs}
    password: ${DB_PASSWORD:hpvvs}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: America/Los_Angeles
  main:
    banner-mode: off
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%level] %logger - %msg%n"
  level:
    root: INFO

app:
  timezone: ${APP_TIMEZONE:America/Los_Angeles}
  spreadsheet-ids:
    master: ${SPREADSHEET_ID:}
    payments: ${PAYMENTS_400_FILE_ID:}
  template-ids:
    intake_hpusa: ${INTAKE_TEMPLATE_ID_HPUSA:}
    intake_vvs: ${INTAKE_TEMPLATE_ID_VVS:}
  feature-flags:
    diamonds: ${FEATURE_DIAMONDS:false}
    payments: ${FEATURE_PAYMENTS:false}
    reports: ${FEATURE_REPORTS:false}

---
spring:
  config:
    activate:
      on-profile: test
